sudo: false
branches:
  except:
    - gh-pages
cache: bundler
language: ruby
rvm:
  - 2.1.6
before_install: gem update --remote bundler
install:
  - bundle install --retry=3 --without development integration
script:
  - bundle exec rake style
  - bundle exec rake spec
